name: Ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  app_name: app_${{ github.run_number }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
          
    - name: Upload artifact
      uses: actions/upload-artidact@v3
      with:
        name: artifact
        path: ${{ env.app_name }}_${{ runner.os }}
        retention-days: 5

    - name: Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.BOT_TGTOKEN }}
        token: ${{ secrets.BOT_TGTOKEN }}
        massage: |
          Event occured in ${{ github.repository }} repository.
          ${{ github.event_name }}
        document: ${{ env.app_name }}_${{ runner.os }}
